<a href="https://colab.research.google.com/github/ZarrinTasnimKhan/AI_212-15-14740sec59D/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import torch
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [4]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [6]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [7]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.3259, 0.3465],
        [0.9757, 0.6492]])

In [8]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.5030, 0.0950, 0.1798],
        [0.5415, 0.7882, 0.2530]])

In [9]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
rand_tensor.shape

torch.Size([2, 3])

In [12]:
rand_tensor.dtype

torch.float32

In [13]:
rand_tensor.device

device(type='cpu')

In [14]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [15]:
 rand_tensor

tensor([[0.5030, 0.0950, 0.1798],
        [0.5415, 0.7882, 0.2530]])

In [16]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.5030, 1.0000, 0.1798],
        [0.5415, 1.0000, 0.2530]])

In [17]:
rand_tensor[0]

tensor([0.5030, 1.0000, 0.1798])

In [18]:
rand_tensor[:,0]

tensor([0.5030, 0.5415])

In [19]:
rand_tensor[...,-1]

tensor([0.1798, 0.2530])

In [20]:
rand_tensor.sum()

tensor(3.4774)

In [21]:
rand_tensor.sum().item()

3.477354049682617

In [22]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.5030, 1.0000, 0.1798, 0.0000, 0.0000, 0.0000],
        [0.5415, 1.0000, 0.2530, 0.0000, 0.0000, 0.0000]])

In [23]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.5030, 1.0000, 0.1798],
        [0.5415, 1.0000, 0.2530],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [24]:
rand_tensor.mul(ones_tensor)

tensor([[0.5030, 1.0000, 0.1798],
        [0.5415, 1.0000, 0.2530]])

In [25]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.2853, 1.3179],
        [1.3179, 1.3573]])

In [26]:
rand_tensor.add_(5)

tensor([[5.5030, 6.0000, 5.1798],
        [5.5415, 6.0000, 5.2530]])

In [27]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [28]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [29]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [30]:
x = torch.empty(1)
print(x)

tensor([-35.7318])


In [31]:
x.size()

torch.Size([1])

In [32]:
x = torch.empty(2,3)
print(x)

tensor([[-6.3084e+01,  3.2775e-41, -6.3070e+01],
        [ 3.2775e-41,  8.9683e-44,  0.0000e+00]])


In [33]:
torch.empty(2,2,3)

tensor([[[5.5495e+30, 3.2768e-41, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [34]:
y=x.view(6)
y

tensor([-6.3084e+01,  3.2775e-41, -6.3070e+01,  3.2775e-41,  8.9683e-44,
         0.0000e+00])

In [35]:
z=x.view(1,-1)
z

tensor([[-6.3084e+01,  3.2775e-41, -6.3070e+01,  3.2775e-41,  8.9683e-44,
          0.0000e+00]])

In [36]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [37]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [38]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [39]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [40]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [41]:
a[1,1].item()

1.0

In [42]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])